[package]
name = "mediawiki"
description = "A MediaWiki client library"
keywords = ["MediaWiki","API"]
categories = ["api-bindings","authentication"]
license = "MIT/Apache-2.0"
repository = "https://github.com/magnusmanske/mediawiki_rust"
exclude = [".DS_Store","*/.DS_Store","*.ini",".gitignore","*.json"]
version = "0.1.15"
authors = ["Magnus Manske <magnusmanske@googlemail.com>"]
edition = "2018"

[dependencies]
serde_json = "1"
reqwest = "0.9.11"
user_agent = "0.6.6"
urlencoding = "1.0.0"
config = "0.9.2"
cookie = "0.11.0"
lazy_static = "1.3.0"
oauth-client = "0.3"
uuid = { version = "0.7.4", features = ["v4"] }
url = "1.7.2"
rust-crypto = "^0.2"
base64 = "0.10.1"
