[package]
name = "mediawiki"
description = "A MediaWiki client library"
keywords = ["MediaWiki","API"]
categories = ["api-bindings","authentication"]
license = "MIT/Apache-2.0"
repository = "https://github.com/magnusmanske/mediawiki_rust"
exclude = [".DS_Store","*/.DS_Store","*.ini",".gitignore","*.json"]
version = "0.1.17"
authors = ["Magnus Manske <magnusmanske@googlemail.com>"]
edition = "2018"

[dependencies]
serde_json = "1"
reqwest = "0.9"
user_agent = "0.9"
urlencoding = "1"
config = "0.9"
cookie = "0.12"
lazy_static = "1.4"
uuid = { version = "0.8", features = ["v4"] }
#url = "1.7.2"
url = "2.1.1"
rust-crypto = "0.2"
base64 = "0.11"
